### ISSUE TITLE
Barrel distortion

### ISSUE THREAD

**Issue by KOuldamer** [IVISO/camcalib#1]
Hello, 
I use the following code to distort an input image using openc cv focntion of radial distortion : 
https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

After, i invert the model using k1, k2, but i can't  recover the original image. Could you check where it's wrong?
def distort_im(im, focal, k1, k2):
     

def distort_im(im, focal, k1, k2):
     
    # distored image size
    M, N, _ = im.shape

    # image center:
    center = [round(N/2), round(M/2)]

    # Creates pixel image grid
    x, y = np.meshgrid(range(N), range(M))
    #  convert pixel coordinates to camera coordinates by camera intrinsic parameters

    x1 = (x - center[0]) / focal
    y1 = (y - center[1]) / focal

    # apply radial distortion 

    r=np.sqrt(x1**2 + y1**2)
    poly_dist=(1.0 + k1 * r + k2 * r**2)

    x2 = x1 *poly_dist
    y2 = y1 *poly_dist
    
    # convert back to pixel coordinates
    # using nearest neighbor interpolation
    u = np.float32(focal * x2 + center[0])
    v = np.float32(focal* y2 + center[1])

    # Remap
    im_distored=cv2.remap(im, u, v, interpolation=cv2.INTER_LINEAR)

    return im_distored  

def undistort_im(im, focal, k1, k2):
     
    # undistored image size
    M, N, _ = im.shape

    # image center:
    center = [round(N/2), round(M/2)]

    # Creates pixel image grid
    x, y = np.meshgrid(range(N), range(M))
    #  convert pixel coordinates to camera coordinates by camera intrinsic parameters

    x1 = (x - center[0]) / focal
    y1 = (y - center[1]) / focal

    # apply radial distortion 

    r=np.sqrt(x1**2 + y1**2)
    poly_dist=(1.0 + k1 * r + k2 * r**2)

    x2 = x1 /poly_dist
    y2 = y1 /poly_dist
    
    # convert back to pixel coordinates
    # using nearest neighbor interpolation
    u = np.float32(focal * x2 + center[0])
    v = np.float32(focal* y2 + center[1])

    # Remap
    im_undistored=cv2.remap(im, u, v, interpolation=cv2.INTER_LINEAR)

    return im_undistored  

if __name__ == "__main__":

    im_path = 'pano_fc5c169792f84e05f7192559ef0b66d3f_225_R_0_P_0_Y_-73.jpg'
   
    im = cv2.imread(im_path)
    
    #intrinsic parameters:
    focal=225

    k1=0.8
    k2=0.02

    im_distored=distort_im(im, focal, k1, k2)

    #plt.imshow(im_distored)
    #plt.show()

    im_undistored=undistort_im(im_distored, focal, k1, k2)
    h, w, _ = im.shape
    out_im = np.zeros([h, w*2, 3], dtype=np.uint8)
    out_im[:, :w, :] = im_distored
    out_im[:, w:, :] = im_undistored

    plt.imshow(out_im)
    plt.show()

**Comment by IVISO** [comment]
You are attempting to find the inverse warp function with undistort_im(). The solution is not as simple as dividing by `poly_dist` to get the inverse distortion. You will have to compute the inverse of the complete distort function. This discussion may help you further: https://math.stackexchange.com/questions/692762/how-to-calculate-the-inverse-of-a-known-optical-distortion-function

Also, I am sorry to say, this is not an issue related to camcalib.
